### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lpotthast** [lpotthast/leptonic#9]
Things planned for the future

- [ ] `Table` component with corresponding `THead`, `TBody`, `TFooter`, `Tr` and `Td`
- [ ] `Kbd` component displaying keyboard chortcuts
- [ ] `ProgressCircle` component, displaying progress in a circular form. Might extend `Progress` with display variants.
- [ ] `Spinner` component. Could this just be an indeterminate ProgressCircle instead?
- [ ] `ContextMenu` for right-click menus
- [ ] `AppMenu` on-top-of-page old-school dropdown-like and expandable menus
- [ ] `Portal` component. Display children at the end of the body or as children of a specified root
- [ ] A theme builder. Interactively manipulate CSS variables provided by `leptos-theme` to build a custsom theme. Export, save, reload, ...

**Comment by lpotthast** [comment]
Definitely! Put it on top of the list.

**Comment by klautcomputing** [comment]
Might I suggest to add a hamburger menu as well? Also thank you for adding ssr to the top of your list! :)

**Comment by opeolluwa** [comment]
How's the theme-builder supposed to workout. This is my first contact with leptonic, it's a huge undertaking.

I'll be glad to help out where I can

**Comment by KOEGlike** [comment]
Could you please add nightly support

**Comment by Benji377** [comment]
@lpotthast is this repository still maintained? 
There have been many reports of the website being unavailable (#84, #81, #79, #72), all unanswered. The PRs have been open for a year now, unanswered.
The last update was 4 months ago on the [migrate-to-leptos-0.8 branch](https://github.com/lpotthast/leptonic/tree/migrate-to-leptos-0.8).
